site_name: Faded's Website
site_description: Faded的网页
site_author: Faded

# 主题配置
theme:
  name: material  # 推荐使用 material 主题

# 插件
plugins:
  - search

# 导航菜单
nav:
  - Home: docs/index.md
  - Tutorials: docs/tutorials.md
  - Notes:
    - Computer System I: Notes/Computer_System_I.md
    - Computer System II: Notes/Computer_System_II.md
    - FDS: Notes/FDS.md
    - ADS: Notes/ADS.md
    - Discreted Math: Notes/Discreted_Math.md
    - General Physics I: Notes/General_Physics_I.md
    - General Physics II: Notes/General_Physics_II.md
    - Commond Line: Notes/Commond_Line.md
  - Projects: 
    - IPaper: Projects/IPaper.md
    - Literature: Projects/Literature.md
  - Blog: docs/blog.md
  - About: docs/about.md

# 额外配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hycrich